article/urls.py
from django.urls import path
from .views import article_list, article_detail, article_archive


app_name = 'article'

urlpatterns = [
    path('', article_list, name='list'),
    path('list/', article_archive, name='archive'),
    path('detail/<slug:slug>', article_detail, name='detail')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls', namespace='article')),
    path('', include('main.urls', namespace='main'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import contact
app_name = 'main'


urlpatterns = [
    path('contact/', contact, name='contact')
]

article/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from ckeditor.fields import RichTextField
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Tags(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='author/')
    content = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, blank=True, related_name='articles')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, related_name='articles')
    tags = models.ManyToManyField(Tags, related_name='tags')
    title = models.CharField(max_length=250)
    content = RichTextField()
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='article/')
    slug = models.SlugField()
    modified_date = models.DateTimeField(auto_now=True)
    is_quote = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return self.title


def pre_save_article(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.title)


pre_save.connect(pre_save_article, sender=Article)


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.SET_NULL, null=True, blank=True, related_name='comments')
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='comments/')
    email = models.EmailField(null=True, blank=True, max_length=50)
    website = models.CharField(null=True, blank=True, max_length=50)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.name

main/models.py
from django.db import models

# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=50, null=True, blank=True)
    message = models.TextField()
    subject = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

article/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'image', 'email', 'website', 'comment']
        exclude = ['article']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            'name': 'name',
            'placeholder': 'Name',
            'id': 'name'
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'name': 'email',
            'placeholder': 'Email',
            'id': 'email'
        })
        self.fields['website'].widget.attrs.update({
            'class': 'form-control',
            'name': 'website',
            'placeholder': 'Website',
            'id': 'website'
        })
        self.fields['comment'].widget.attrs.update({
            'class': 'form-control w-100',
            'name': 'comment',
            'placeholder': 'Comment',
            'id': 'comment',
            'cols': 30,
            'rows': 9
        })

        self.fields['image'].widget.attrs.update({
            'class': 'form-control w-100',
            'name': 'image',
            'id': 'image'
        })

main/forms.py
from django import forms
from main.models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            'name': 'name',
            'placeholder': 'Enter your name',
            'id': 'name'
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'name': 'email',
            'placeholder': 'Enter your email address',
            'id': 'email'
        })
        self.fields['subject'].widget.attrs.update({
            'class': 'form-control',
            'name': 'subject',
            'placeholder': 'Enter your subject',
            'id': 'subject'
        })
        self.fields['message'].widget.attrs.update({
            'class': 'form-control w-100',
            'name': 'message',
            'placeholder': 'Enter your message',
            'id': 'message',
            'cols': 30,
            'rows': 9
        })

article/views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from .models import Article, Comment, Tags, Category
from .forms import CommentForm
from django.core.paginator import Paginator
# Create your views here.


def article_list(request):
    articles = Article.objects.order_by('-id')
    categories = Category.objects.all()
    print(categories.values())
    for i in articles.values():
        print(i['category_id'])
    ctx = {
        'articles': articles
    }

    return render(request, 'article/index.html', ctx)


def article_archive(request):
    articles = Article.objects.order_by('-id')
    popular_articles = Article.objects.order_by('-id')
    categories = Category.objects.all()
    tags = Tags.objects.all()

    paginator = Paginator(articles, per_page=2)
    articles = paginator.get_page(request.GET.get('page'))

    q = request.GET.get('q')
    cat = request.GET.get('cat')
    tag = request.GET.get('tag')
    if q:
        articles = articles.filter(title__contains=q)
    if cat:
        articles = articles.filter(category__name=cat)
    if tag:
        articles = articles.filter(tags__name=tag)
    ctx = {
        'articles': articles,
        'popular_articles': popular_articles,
        'categories': categories,
        'tags': tags
    }
    return render(request, 'article/archive.html', ctx)


def article_detail(request, slug):
    article = get_object_or_404(Article, slug=slug)
    categories = Category.objects.all()
    tags = Tags.objects.all()
    form = CommentForm()
    q = request.GET.get('q')
    if q:
        resolve = resolve_url('/list/?q='+q)
        return redirect(resolve)
    if request.method == 'POST':
        print(request.POST)
        form = CommentForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.save()
            print(comment)
            return redirect('article:detail', slug=article.slug)
    ctx = {
        'article': article,
        'form': form,
        'categories': categories,
        'tags': tags
    }

    return render(request, 'article/single-blog.html', ctx)

main/views.py
from django.shortcuts import render, redirect
from .models import Contact
from .forms import ContactForm
# Create your views here.


def contact(request):
    form = ContactForm()
    print('work')
    if request.method == 'POST':
        print(request.POST)
        print(form)
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('.')

    ctx = {
        'form': form
    }
    return render(request, 'main/contact.html', ctx)

templates/article/archive.html
    {% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="breadcrumb breadcrumb_bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb_iner">
                    <div class="breadcrumb_iner_item">
                        <h2>Post Archive</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="all_post archive_post">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    {% if articles.count != 0 %}

                    {% for article in articles %}
                        
                    	<div class="col-lg-6">
                            <div class="single_catagory_post post_2">
                                <div class="category_post_img">
                                    <img style="height: 300px" src="{{ article.image.url }}" alt>
                                    <a href="/" class="category_btn">{{ article.category }}</a>
                                </div>
                                <div class="post_text_1 pr_30">
                                    <p><span>{{ article.author }}</span> / {{ article.created_at|date:'F d, Y' }}</p>
                                    <a href="{% url 'article:detail' article.slug %}">
                                        <h3>{{ article.title }}</h3>
                                    </a>
                                    <div class="post_icon">
                                        <ul>
                                            <li><i class="ti-comment"></i>{{ article.comments.values.count }} Comment</li>
                                            <li><i class="ti-heart"></i>0 Like</li>
                                            <li><i class="ti-export"></i>Share</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    {% endfor %}

                    {% elif articles.count == 0 %}
                        <div>
                            <h1>No articles</h1>
                        </div>
                    {% endif %}
                
                </div>
                {% include 'pagination.html' %}
            </div>
            <div class="col-lg-4">
                <div class="sidebar_widget">
                    <div class="sidebar_tittle">
                        <h3>Search Objects</h3>
                    </div>
                    <form >
                        <div class="form-group">
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" name="q" placeholder="Search Keyword"
                                       onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Keyword'">
                                <div class="input-group-append">
                                    <button class="btn" type="submit"><i class="ti-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="sidebar_tittle">
                        <h3>Popular Feeds</h3>
                    </div>

                    {% for article in popular_articles|slice:5 %}

                    	<div class="single_catagory_post post_2 single_border_bottom">
                            <div class="category_post_img">
                                <img src="{{ article.image.url }}" alt>
                            </div>
                            <div class="post_text_1 pr_30">
                                <p><span>{{ article.author }}</span> / {{ article.created_at|date:'F d, Y' }}</p>
                                <a href="/">
                                    <h3>{{ article.title }}</h3>
                                </a>
                            </div>
                        </div>

                    {% endfor %}


                    <div class="sidebar_tittle">
                        <h3>Categories</h3>
                    </div>
                    <div class="single_catagory_item category">
                        <ul class="list-unstyled">
                        
                            {% for category in categories %}
                                
                            	<li><a href="?cat={{ category.name }}">{{ category.name }} ({{ category.articles.count }})</a></li>
                                
                            {% endfor %}
                                                        
                        </ul>
                    </div>
                    <div class="sidebar_tittle">
                        <h3>Popular Tags</h3>
                    </div>
                    <div class="single_catagory_item tags">
                        <ul class="list-unstyled">
                            
                            {% for tag in tags %}
                                
                            	<li><a href="?tag={{ tag.name }}">{{ tag.name }}</a></li>
                                
                            {% endfor %}
                        
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/article/category.html
<!doctype html>
<html lang="en">

<!-- Mirrored from preview.colorlib.com/theme/daren/category.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 19 Jan 2024 05:56:25 GMT -->
<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>DarEn BLOG || CATEGORY</title>
<link rel="icon" href="img/favicon.png">

<link rel="stylesheet" href="css/bootstrap.min.css">

<link rel="stylesheet" href="css/animate.css">

<link rel="stylesheet" href="css/owl.carousel.min.css">

<link rel="stylesheet" href="css/themify-icons.css">

<link rel="stylesheet" href="css/liner_icon.css">
<link rel="stylesheet" href="css/search.css">

<link rel="stylesheet" href="css/slick.css">

<link rel="stylesheet" href="css/style.css">
<script nonce="5cd48f12-526e-46de-97cb-39328efe92e6">try { (function(w,d){!function(o,p,q,r){o[q]=o[q]||{};o[q].executed=[];o.zaraz={deferred:[],listeners:[]};o.zaraz.q=[];o.zaraz._f=function(s){return async function(){var t=Array.prototype.slice.call(arguments);o.zaraz.q.push({m:s,a:t})}};for(const u of["track","set","debug"])o.zaraz[u]=o.zaraz._f(u);o.zaraz.init=()=>{var v=p.getElementsByTagName(r)[0],w=p.createElement(r),x=p.getElementsByTagName("title")[0];x&&(o[q].t=p.getElementsByTagName("title")[0].text);o[q].x=Math.random();o[q].w=o.screen.width;o[q].h=o.screen.height;o[q].j=o.innerHeight;o[q].e=o.innerWidth;o[q].l=o.location.href;o[q].r=p.referrer;o[q].k=o.screen.colorDepth;o[q].n=p.characterSet;o[q].o=(new Date).getTimezoneOffset();if(o.dataLayer)for(const B of Object.entries(Object.entries(dataLayer).reduce(((C,D)=>({...C[1],...D[1]})),{})))zaraz.set(B[0],B[1],{scope:"page"});o[q].q=[];for(;o.zaraz.q.length;){const E=o.zaraz.q.shift();o[q].q.push(E)}w.defer=!0;for(const F of[localStorage,sessionStorage])Object.keys(F||{}).filter((H=>H.startsWith("_zaraz_"))).forEach((G=>{try{o[q]["z_"+G.slice(7)]=JSON.parse(F.getItem(G))}catch{o[q]["z_"+G.slice(7)]=F.getItem(G)}}));w.referrerPolicy="origin";w.src="https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z="+btoa(encodeURIComponent(JSON.stringify(o[q])));v.parentNode.insertBefore(w,v)};["complete","interactive"].includes(p.readyState)?zaraz.init():o.addEventListener("DOMContentLoaded",zaraz.init)}(w,d,"zarazData","script");})(window,document) } catch (err) {
      console.error('Failed to run Cloudflare Zaraz: ', err)
      fetch('/cdn-cgi/zaraz/t', {
        credentials: 'include',
        keepalive: true,
        method: 'GET',
      })
    };</script></head>
<body>

<header class="main_menu">
<div class="container">
<div class="row align-items-center">
<div class="col-lg-12">
<nav class="navbar navbar-expand-lg navbar-light">
<a class="navbar-brand" href="index-2.html"> <img src="img/logo.png" alt="logo"> </a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse main-menu-item justify-content-center" id="navbarSupportedContent">
<ul class="navbar-nav">
<li class="nav-item active">
<a class="nav-link" href="index-2.html">Home</a>
</li>
<li class="nav-item">
<a class="nav-link" href="archive.html">Archive</a>
</li>
<li class="nav-item">
<a class="nav-link" href="category.html"> Category</a>
</li>
<li class="nav-item">
<a class="nav-link" href="../main/contact.html">Contact</a>
</li>
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
Pages
</a>
<div class="dropdown-menu" aria-labelledby="navbarDropdown">
<a class="dropdown-item" href="single-blog.html">Single blog</a>
<a class="dropdown-item" href="elements.html">elements</a>
</div>
</li>
</ul>
</div>
<div class="header_social_icon d-none d-sm-block">
<ul>
<li>
<div id="wrap">
<form action="#" autocomplete="on">
<input id="search" name="search" type="text" placeholder="Search here"><span class="ti-search"></span>
</form>
</div>
</li>
<li><a href="#" class="d-none d-lg-block"><i class="ti-facebook"></i></a></li>
<li><a href="#" class="d-none d-lg-block"> <i class="ti-twitter-alt"></i></a></li>
<li><a href="#" class="d-none d-lg-block"><i class="ti-instagram"></i></a></li>
<li><a href="#" class="d-none d-lg-block"><i class="ti-skype"></i></a></li>
</ul>
</div>
</nav>
</div>
</div>
</div>
</header>


<section class="breadcrumb breadcrumb_bg">
<div class="container">
<div class="row">
<div class="col-lg-12">
<div class="breadcrumb_iner text-center">
<div class="breadcrumb_iner_item">
<h2>Category Page</h2>
</div>
</div>
</div>
</div>
</div>
</section>


<section class="all_post section_padding">
<div class="container">
<div class="row">
<div class="col-lg-8">
<div class="single_post media post_3">
<div class="single_post_img">
<img src="img/post/post_11.png" alt>
<a href="category.html" class="category_btn">abstract design</a>
</div>
<div class="post_text_1 media-body align-self-center">
<p><span> By Michal</span> / March 30 , 2019</p>
<a href="single-blog.html">
<h3>Called face there light this
said wherein replenish sadin
made green grass</h3>
</a>
<div class="post_icon">
<ul>
<li><i class="ti-comment"></i>2 Comment</li>
<li><i class="ti-heart"></i>0 Like</li>
<li><i class="ti-export"></i>Share</li>
</ul>
</div>
</div>
</div>
<div class="single_post media post_3">
<div class="single_post_img">
<img src="img/post/post_12.png" alt>
<a href="category.html" class="category_btn">abstract design</a>
</div>
<div class="post_text_1 media-body align-self-center">
<p><span> By Michal</span> / March 30 , 2019</p>
<a href="single-blog.html">
<h3>Called face there light this
said wherein replenish sadin
made green grass</h3>
</a>
<div class="post_icon">
<ul>
<li><i class="ti-comment"></i>2 Comment</li>
<li><i class="ti-heart"></i>0 Like</li>
<li><i class="ti-export"></i>Share</li>
</ul>
</div>
</div>
</div>
<div class="single_post media post_3">
<div class="single_post_img">
<img src="img/post/post_13.png" alt>
<a href="category.html" class="category_btn">abstract design</a>
</div>
<div class="post_text_1 media-body align-self-center">
<p><span> By Michal</span> / March 30 , 2019</p>
<a href="single-blog.html">
<h3>Called face there light this
said wherein replenish sadin
made green grass</h3>
</a>
<div class="post_icon">
<ul>
<li><i class="ti-comment"></i>2 Comment</li>
<li><i class="ti-heart"></i>0 Like</li>
<li><i class="ti-export"></i>Share</li>
</ul>
</div>
</div>
</div>
<div class="single_post media post_3">
<div class="single_post_img">
<img src="img/post/post_14.png" alt>
<a href="category.html" class="category_btn">abstract design</a>
</div>
<div class="post_text_1 media-body align-self-center">
<p><span> By Michal</span> / March 30 , 2019</p>
<a href="single-blog.html">
<h3>Called face there light this
said wherein replenish sadin
made green grass</h3>
</a>
<div class="post_icon">
<ul>
<li><i class="ti-comment"></i>2 Comment</li>
<li><i class="ti-heart"></i>0 Like</li>
<li><i class="ti-export"></i>Share</li>
</ul>
</div>
</div>
</div>
<div class="single_post media post_3">
<div class="single_post_img">
<img src="img/post/post_15.png" alt>
<a href="category.html" class="category_btn">abstract design</a>
</div>
<div class="post_text_1 media-body align-self-center">
<p><span> By Michal</span> / March 30 , 2019</p>
<a href="single-blog.html">
<h3>Called face there light this
said wherein replenish sadin
made green grass</h3>
</a>
<div class="post_icon">
<ul>
<li><i class="ti-comment"></i>2 Comment</li>
<li><i class="ti-heart"></i>0 Like</li>
<li><i class="ti-export"></i>Share</li>
</ul>
</div>
</div>
</div>
<div class="load_btn text-center">
<a href="#" class="btn_1">LOADING MORE <i class="ti-angle-right"></i></a>
</div>
</div>
<div class="col-lg-4">
<div class="sidebar_widget">
<div class="sidebar_tittle">
<h3>Search Objects</h3>
</div>
<form action="#">
<div class="form-group">
<div class="input-group mb-3">
<input type="text" class="form-control" placeholder="Search Keyword" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Keyword'">
<div class="input-group-append">
<button class="btn" type="button"><i class="ti-search"></i></button>
</div>
</div>
</div>
</form>
<div class="sidebar_tittle">
<h3>Popular Feeds</h3>
</div>
<div class="single_catagory_post post_2 single_border_bottom">
<div class="category_post_img">
<img src="img/sidebar/sidebar_1.png" alt>
</div>
<div class="post_text_1 pr_30">
<p><span> By Michal</span> / March 30 , 2019</p>
<a href="single-blog.html">
<h3>Subdue lesser beast winged
bearing meat tree one</h3>
</a>
</div>
</div>
<div class="single_catagory_post post_2 single_border_bottom">
<div class="category_post_img">
<img src="img/sidebar/sidebar_2.png" alt>
</div>
<div class="post_text_1 pr_30">
<p><span> By Michal</span> / March 30 , 2019</p>
<a href="single-blog.html">
<h3>Subdue lesser beast winged
bearing meat tree one</h3>
</a>
</div>
</div>
<div class="single_catagory_post post_2">
<div class="category_post_img">
<img src="img/sidebar/sidebar_3.png" alt>
</div>
<div class="post_text_1 pr_30">
<p><span> By Michal</span> / March 30 , 2019</p>
<a href="single-blog.html">
<h3>Subdue lesser beast winged
bearing meat tree one</h3>
</a>
</div>
</div>
<div class="sidebar_tittle">
<h3>Categories</h3>
</div>
<div class="single_catagory_item category">
<ul class="list-unstyled">
<li><a href="single-blog.html">Culture (12)</a></li>
<li><a href="single-blog.html">Creative Design (15)</a></li>
<li><a href="single-blog.html">Illustration (25)</a></li>
<li><a href="single-blog.html">Production (16)</a></li>
<li><a href="single-blog.html">Mangement (10)</a></li>
<li><a href="single-blog.html">Branding (15)</a></li>
</ul>
</div>
<div class="sidebar_tittle">
<h3>Popular Tags</h3>
</div>
<div class="single_catagory_item tags">
<ul class="list-unstyled">
<li><a href="single-blog.html">Nature</a></li>
<li><a href="single-blog.html">business</a></li>
<li><a href="single-blog.html">tech</a></li>
<li><a href="single-blog.html">News</a></li>
<li><a href="single-blog.html">html</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</section>


<footer class="footer-area">
<div class="container">
<div class="row">
<div class="col-xl-4 col-sm-6">
<div class="single-footer-widget footer_1">
<h4>About Me</h4>
<p>Do you want to be even more successful? Learn to love learning and growth.
The more effort you put into improving your skills, the bigger the payoff
you will get. Realize that things will be hard at first, but the rewards
will be worth it.</p>
</div>
</div>
<div class="col-xl-4 col-sm-6">
<div class="single-footer-widget footer_2">
<h4>Contact us</h4>
<div class="contact_info">
<span class="ti-home"></span>
<h5>Los angeles, United States</h5>
<p>659, Rocky beach bullevard, santa monica, Rocky beach, USA.</p>
</div>
<div class="contact_info">
<span class="ti-headphone-alt"></span>
<h5>+44 6532 986 652</h5>
<p>Mon to Fri 9am to 6 pm.</p>
</div>
</div>
</div>
<div class="col-xl-4 col-sm-8">
<div class="single-footer-widget footer_3">
<h4>Newsletter</h4>
<p>Stay updated with our latest trends The more effort you put into
improving your skills, the bigger the payoff you will get realize that things.</p>
<form action="#">
<div class="form-group">
<div class="input-group mb-3">
<input type="text" class="form-control" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
<div class="input-group-append">
<button class="btn" type="button"><span class="lnr lnr-arrow-right"></span></button>
</div>
</div>
</div>
</form>
</div>
</div>
</div>
<div class="row align-items-center">
<div class="col-lg-12">
<div class="copyright_part_text text-center">
<p class="footer-text m-0">
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com/" target="_blank">Colorlib</a>
</p>
</div>
</div>
</div>
</div>
</footer>



<script src="js/jquery-1.12.1.min.js"></script>

<script src="js/popper.min.js"></script>

<script src="js/bootstrap.min.js"></script>

<script src="js/custom.js"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317" integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA==" data-cf-beacon='{"rayId":"847cd47f5ccc715e","version":"2024.1.0","token":"cd0b4b3a733644fc843ef0b185f98241"}' crossorigin="anonymous"></script>
</body>

<!-- Mirrored from preview.colorlib.com/theme/daren/category.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 19 Jan 2024 05:56:25 GMT -->
</html>

templates/navbar.html
{% load static %}

<header class="main_menu">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="navbar-brand" href="/"> <img src="{% static 'img/logo.png' %}" alt="logo"> </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse main-menu-item justify-content-center"
                         id="navbarSupportedContent">
                        <ul class="navbar-nav">
                            <li class="nav-item active">
                                <a class="nav-link" href="/">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'article:archive' %}">Archive</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'main:contact' %}">Contact</a>
                            </li>
                        </ul>
                    </div>
                    <div class="header_social_icon d-none d-sm-block">
                        <ul>
                            <li>
                                <div id="wrap">
                                    <form action="#" autocomplete="on">
                                        <input id="search" name="search" type="text" placeholder="Search here"><span
                                            class="ti-search"></span>
                                    </form>
                                </div>
                            </li>
                            <li><a href="#" class="d-none d-lg-block"><i class="ti-facebook"></i></a></li>
                            <li><a href="#" class="d-none d-lg-block"> <i class="ti-twitter-alt"></i></a></li>
                            <li><a href="#" class="d-none d-lg-block"><i class="ti-instagram"></i></a></li>
                            <li><a href="#" class="d-none d-lg-block"><i class="ti-skype"></i></a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>

templates/pagination.html
<ul style="display: flex; gap: 10px; text-align: center; align-items: center; justify-content: center">
    {% if articles.has_previous %}
      <li><a href="?page={{ articles.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in articles.paginator.page_range %}
      {% if articles.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if articles.has_next %}
      <li><a href="?page={{ articles.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>